server:
  port: 8080
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://stockticks.c9ghgljnm8jc.us-east-2.rds.amazonaws.com:5432/stockticks
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: bodacious
  servlet:
    multipart:
      max-file-size: 3MB